services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: usersdb
    networks:
      - backend
  node:
    build: .
    container_name: node
    ports:
      - 3000:3000
    depends_on:
      - mongo
    restart: always
    networks:
      - backend

networks:
  backend:
    driver: bridge
